window.embeddedBetHistory = [
  {
    "bet_id": "5629b7ed117791a3",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T10:20:08.891Z",
    "opening_odds": 21,
    "opening_model_price": 14.49,
    "opening_ev": 44.93,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 21,
    "current_model_price": 14.49,
    "current_ev": 44.93,
    "current_qi": 85,
    "last_seen_at": "2026-06-14T02:39:18.581Z"
  },
  {
    "bet_id": "15962282b61f0b9f",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Curaçao to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T23:08:30.126Z",
    "opening_odds": 41,
    "opening_model_price": 34.28,
    "opening_ev": 19.6,
    "opening_qi": 78,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 41,
    "current_model_price": 34.28,
    "current_ev": 19.6,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T02:39:18.581Z"
  },
  {
    "bet_id": "cb0529d26ebe1a93",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 13,
    "opening_model_price": 10.82,
    "opening_ev": 20.15,
    "opening_qi": 80,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 12,
    "current_model_price": 10.82,
    "current_ev": 10.91,
    "current_qi": 77,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null
  },
  {
    "bet_id": "6c840404fb575384",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Cape Verde to Win",
    "au_bookie": "Sportsbet / TAB",
    "first_seen_at": "2026-06-13T16:45:59.182Z",
    "opening_odds": 26,
    "opening_model_price": 24.71,
    "opening_ev": 5.22,
    "opening_qi": 70,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 26,
    "current_model_price": 24.71,
    "current_ev": 5.22,
    "current_qi": 70,
    "last_seen_at": "2026-06-14T02:39:18.581Z"
  },
  {
    "bet_id": "59153a72676e781d",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Iraq to Win",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-13T15:10:30.583Z",
    "opening_odds": 15,
    "opening_model_price": 14.14,
    "opening_ev": 6.08,
    "opening_qi": 72,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 15,
    "current_model_price": 14.14,
    "current_ev": 6.08,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T02:39:18.581Z"
  },
  {
    "bet_id": "7472d2164ed6dbd6",
    "match_name": "Canada vs Qatar",
    "kickoff_time_aest": "2026-06-19T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T21:42:33.439Z",
    "opening_odds": 5.75,
    "opening_model_price": 5.25,
    "opening_ev": 9.52,
    "opening_qi": 78,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 5.75,
    "current_model_price": 5.25,
    "current_ev": 9.52,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T02:39:18.581Z"
  },
  {
    "bet_id": "0cd2e7e6b50a9dfa",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Omar Alderete: To Get Carded",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 3.76,
    "opening_model_price": 2.6,
    "opening_ev": 44.62,
    "opening_qi": 95,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 3.76,
    "current_model_price": 2.6,
    "current_ev": 44.62,
    "current_qi": 95,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 3.76,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "60f23ca7387fc316",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "USA to Win",
    "au_bookie": "Neds",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 2,
    "opening_model_price": 1.78,
    "opening_ev": 12.36,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 2,
    "current_model_price": 1.78,
    "current_ev": 12.36,
    "current_qi": 86,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 2,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "c7bab8ab5c37ec1e",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Spread",
    "target_selection": "USA -0.5",
    "au_bookie": "Ladbrokes",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.78,
    "opening_ev": 9.55,
    "opening_qi": 83,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 1.95,
    "current_model_price": 1.78,
    "current_ev": 9.55,
    "current_qi": 83,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 1.95,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "0f3625818db9b60f",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Exact Score",
    "target_selection": "USA 1-0",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 6.5,
    "opening_model_price": 5.8,
    "opening_ev": 12.07,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 6.5,
    "current_model_price": 5.8,
    "current_ev": 12.07,
    "current_qi": 79,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 6.5,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "af3321b011cd184b",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Qatar to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T19:47:54.872Z",
    "opening_odds": 91,
    "opening_model_price": 14.66,
    "opening_ev": 520.74,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 251,
    "estimated_clv_percent": -63.75,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 251,
    "current_model_price": 14.66,
    "current_ev": 1612.14,
    "current_qi": 100,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "6c00d0a6d298095a",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T20:56:09.020Z",
    "opening_odds": 21,
    "opening_model_price": 6.47,
    "opening_ev": 224.57,
    "opening_qi": 99,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 21,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 21,
    "current_model_price": 6.47,
    "current_ev": 224.57,
    "current_qi": 99,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "1b6e90811728cb18",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "Sportsbet / PointsBet",
    "first_seen_at": "2026-06-13T15:10:30.583Z",
    "opening_odds": 7,
    "opening_model_price": 6.47,
    "opening_ev": 8.19,
    "opening_qi": 76,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 7,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 7,
    "current_model_price": 6.47,
    "current_ev": 8.19,
    "current_qi": 76,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "1053824585cb3671",
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "Brazil to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.48,
    "opening_model_price": 1.42,
    "opening_ev": 4.23,
    "opening_qi": 73,
    "closing_odds": 1.69,
    "closing_captured_at": "2026-06-13T21:42:31.932Z",
    "clv_percent": -12.43,
    "current_odds": 31,
    "current_model_price": 1.42,
    "current_ev": 2083.1,
    "current_qi": 100,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "result_status": "lost",
    "result_detail": "ESPN final: Brazil 1-1 Morocco.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760419/morocco-brazil",
    "closing_source": "Confirmed live check 17 min before kickoff",
    "closing_status": "confirmed",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "settled_at": "2026-06-14T01:02:30.916Z"
  },
  {
    "bet_id": "e57f1fc9ba28e787",
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Morocco to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-14T00:12:23.782Z",
    "opening_odds": 21,
    "opening_model_price": 5.76,
    "opening_ev": 264.58,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 21,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Brazil 1-1 Morocco.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760419/morocco-brazil",
    "current_odds": 21,
    "current_model_price": 5.76,
    "current_ev": 264.58,
    "current_qi": 100,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T01:02:30.916Z"
  },
  {
    "bet_id": "e6a2acee4c7ca32a",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Haiti to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-14T02:39:18.581Z",
    "opening_odds": 26,
    "opening_model_price": 5.9,
    "opening_ev": 340.68,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 26,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 26,
    "current_model_price": 5.9,
    "current_ev": 340.68,
    "current_qi": 100,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff"
  },
  {
    "bet_id": "43fd442e8ac065fa",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-14T01:39:23.269Z",
    "opening_odds": 4.75,
    "opening_model_price": 4.33,
    "opening_ev": 9.7,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 5.25,
    "estimated_clv_percent": -9.52,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 5.25,
    "current_model_price": 4.33,
    "current_ev": 21.25,
    "current_qi": 84,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff"
  },
  {
    "bet_id": "8a8009156f469471",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "Scotland to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.75,
    "opening_model_price": 1.65,
    "opening_ev": 6.06,
    "opening_qi": 78,
    "closing_odds": 1.53,
    "closing_captured_at": "2026-06-14T00:31:11.998Z",
    "clv_percent": 14.38,
    "current_odds": 1.2,
    "current_model_price": 1.65,
    "current_ev": -27.27,
    "current_qi": 0,
    "last_seen_at": "2026-06-14T02:39:18.581Z",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "closing_source": "Confirmed live check 29 min before kickoff",
    "closing_status": "confirmed",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null
  }
];
