window.embeddedBetHistory = [
  {
    "bet_id": "89da5785c9e418e9",
    "match_name": "Uzbekistan vs Colombia",
    "kickoff_time_aest": "2026-06-18T12:00:00",
    "market_matrix": "Main Match",
    "target_selection": "Uzbekistan or Draw",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-17T21:47:35.028Z",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "SportsBet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "opening_odds": 3.2,
    "opening_model_price": 2.57,
    "opening_ev": 24.51,
    "opening_qi": 70,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "estimated_qi": null,
    "current_odds": 3.2,
    "current_model_price": 2.57,
    "current_ev": 24.51,
    "current_qi": 70,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "df04657d14748ae2",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-17T06:52:01.396Z",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "opening_odds": 1.75,
    "opening_model_price": 1.58,
    "opening_ev": 10.76,
    "opening_qi": 80,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "estimated_qi": null,
    "current_odds": 1.8,
    "current_model_price": 1.57,
    "current_ev": 14.65,
    "current_qi": 86,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "26cc8c5c17f96e06",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-17T06:52:01.396Z",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "opening_odds": 1.28,
    "opening_model_price": 1.21,
    "opening_ev": 5.79,
    "opening_qi": 74,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "estimated_qi": null,
    "current_odds": 1.28,
    "current_model_price": 1.2,
    "current_ev": 6.67,
    "current_qi": 77,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "c0e03e92b1c2deb8",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:44:14.514Z",
    "opening_odds": 1.46,
    "opening_model_price": 1.33,
    "opening_ev": 9.77,
    "opening_qi": 82,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.44,
    "current_model_price": 1.33,
    "current_ev": 8.27,
    "current_qi": 79,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_qi": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "96a7f19ba0747777",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:44:14.514Z",
    "opening_odds": 2.35,
    "opening_model_price": 1.98,
    "opening_ev": 18.69,
    "opening_qi": 76,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.35,
    "current_model_price": 1.96,
    "current_ev": 19.9,
    "current_qi": 78,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_qi": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "71d9b14cc64d4a47",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T23:47:57.621Z",
    "opening_odds": 2.05,
    "opening_model_price": 1.82,
    "opening_ev": 12.64,
    "opening_qi": 76,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "estimated_qi": null,
    "current_odds": 2.05,
    "current_model_price": 1.87,
    "current_ev": 9.63,
    "current_qi": 71,
    "last_seen_at": "2026-06-17T21:47:35.028Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "0cd2e7e6b50a9dfa",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Omar Alderete: To Get Carded",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 3.76,
    "opening_model_price": 2.6,
    "opening_ev": 44.62,
    "opening_qi": 95,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 3.76,
    "current_model_price": 2.6,
    "current_ev": 44.62,
    "current_qi": 82,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z",
    "closing_qi": null,
    "closing_bookie": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_qi": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "Sportsbet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "60f23ca7387fc316",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "USA to Win",
    "au_bookie": "Neds",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 2,
    "opening_model_price": 1.78,
    "opening_ev": 12.36,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 2,
    "current_model_price": 1.78,
    "current_ev": 12.36,
    "current_qi": 77,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z",
    "closing_qi": null,
    "closing_bookie": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_qi": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "Neds price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "c7bab8ab5c37ec1e",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Spread",
    "target_selection": "USA -0.5",
    "au_bookie": "Ladbrokes",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.78,
    "opening_ev": 9.55,
    "opening_qi": 83,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 1.95,
    "current_model_price": 1.78,
    "current_ev": 9.55,
    "current_qi": 72,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z",
    "closing_qi": null,
    "closing_bookie": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_qi": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "Ladbrokes price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "1053824585cb3671",
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "Brazil to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.48,
    "opening_model_price": 1.42,
    "opening_ev": 4.23,
    "opening_qi": 73,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 1.48,
    "current_model_price": 1.42,
    "current_ev": 4.23,
    "current_qi": 73,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "result_status": "lost",
    "result_detail": "FIFA final: Brazil 1-1 Morocco.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M07-BRA-V-MAR%20POST-V2.pdf",
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "settled_at": "2026-06-14T01:02:30.916Z",
    "closing_qi": null,
    "closing_bookie": null,
    "estimated_qi": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "rejected_current_odds": 31,
    "current_price_note": "Post-start or stale outlier rejected; restored opening price for clean history display.",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "PointsBet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "f0b5ffaa8dbd7167",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:43:37.084Z",
    "opening_odds": 1.85,
    "opening_model_price": 1.44,
    "opening_ev": 28.47,
    "opening_qi": 99,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: Spain 0-0 Cape Verde.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760428/cape-verde-spain",
    "current_odds": 1.95,
    "current_model_price": 1.4,
    "current_ev": 39.29,
    "current_qi": 99,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_qi": null,
    "settled_at": "2026-06-15T20:03:55.026Z",
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "77ebc4922937905d",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 4.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:43:37.084Z",
    "opening_odds": 1.36,
    "opening_model_price": 1.18,
    "opening_ev": 15.25,
    "opening_qi": 96,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: Spain 0-0 Cape Verde.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760428/cape-verde-spain",
    "current_odds": 1.4,
    "current_model_price": 1.16,
    "current_ev": 20.69,
    "current_qi": 99,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_qi": null,
    "settled_at": "2026-06-15T20:03:55.026Z",
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "b71fba2ccf324164",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:43:37.084Z",
    "opening_odds": 3,
    "opening_model_price": 2.11,
    "opening_ev": 42.18,
    "opening_qi": 87,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: Spain 0-0 Cape Verde.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760428/cape-verde-spain",
    "current_odds": 3.2,
    "current_model_price": 2.02,
    "current_ev": 58.42,
    "current_qi": 89,
    "last_seen_at": "2026-06-15T23:17:28.073Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "estimated_qi": null,
    "settled_at": "2026-06-15T20:03:55.026Z",
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market"
  },
  {
    "bet_id": "863157d589fdae0d",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Main Match",
    "target_selection": "Cape Verde or Draw",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-16T00:08:07.183Z",
    "opening_odds": 9,
    "opening_model_price": 3.74,
    "opening_ev": 140.64,
    "opening_qi": 71,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "won",
    "result_detail": "ESPN final: Spain 0-0 Cape Verde.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760428/cape-verde-spain",
    "estimated_qi": null,
    "rejected_current_odds": null,
    "current_odds": 9,
    "current_model_price": 3.74,
    "current_ev": 140.64,
    "current_qi": 71,
    "current_price_note": "Post-start or stale outlier rejected; restored opening price for clean history display.",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "SportsBet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "missing_sharp_market",
    "settled_at": "2026-06-16T12:10:06.227Z"
  },
  {
    "bet_id": "849845aafc846fae",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-17T11:31:20.041Z",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "SportsBet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "opening_odds": 2.88,
    "opening_model_price": 2.38,
    "opening_ev": 21.01,
    "opening_qi": 70,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": null,
    "latest_pre_kickoff_at": null,
    "latest_pre_kickoff_bookie": null,
    "latest_pre_kickoff_clv_percent": null,
    "latest_pre_kickoff_qi": null,
    "latest_pre_kickoff_source": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "ESPN final: Spain 0-0 Cape Verde.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760428/cape-verde-spain",
    "estimated_qi": null,
    "rejected_current_odds": null,
    "current_odds": 2.88,
    "current_model_price": 2.38,
    "current_ev": 21.01,
    "current_qi": 70,
    "current_price_note": "Post-start or stale outlier rejected; restored opening price for clean history display.",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "missing_sharp_close",
    "closing_reference_type": "missing_sharp_market",
    "settled_at": "2026-06-17T11:32:40.417Z"
  },
  {
    "bet_id": "6ecc09ef5590e849",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Chris Wood: Anytime Goal",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-16T12:00:12.667Z",
    "save_rule": "Saved from user confirmed backed price because opening QI was 70+.",
    "opening_source": "User reported backed Sportsbet price $4.24.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "opening_odds": 4.24,
    "opening_model_price": 2.93,
    "opening_ev": 44.71,
    "opening_qi": 72,
    "current_odds": 3.75,
    "current_model_price": 2.93,
    "current_ev": 27.99,
    "current_qi": 68,
    "last_seen_at": "2026-06-16T12:00:12.667Z",
    "latest_pre_kickoff_odds": 3.75,
    "latest_pre_kickoff_at": "2026-06-16T12:00:12.667Z",
    "latest_pre_kickoff_bookie": "Sportsbet",
    "latest_pre_kickoff_clv_percent": 13.07,
    "latest_pre_kickoff_qi": 68,
    "latest_pre_kickoff_source": "User confirmed current Sportsbet price before game time.",
    "tab_current_odds": 3.15,
    "tab_current_move_percent": 34.6,
    "closing_odds": null,
    "closing_captured_at": null,
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "Waiting for Betfair/Pinnacle around 5 minutes before game time",
    "closing_status": "awaiting_sharp_close",
    "closing_reference_type": "pending_sharp_market",
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "lost",
    "result_detail": "FIFA final: Iran 2-2 New Zealand.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M15-IRN-V-NZL.pdf",
    "settled_at": "2026-06-16T12:00:12.667Z",
    "manual_user_saved": true
  },
  {
    "bet_id": "14c56e5c79a33dbf",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:43:37.084Z",
    "opening_odds": 1.52,
    "opening_model_price": 1.4,
    "opening_ev": 8.57,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 1.46,
    "estimated_clv_percent": 4.11,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "current_odds": 1.46,
    "current_model_price": 1.26,
    "current_ev": 15.87,
    "current_qi": 95,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "latest_pre_kickoff_odds": 1.46,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "TAB",
    "latest_pre_kickoff_clv_percent": 4.11,
    "latest_pre_kickoff_qi": 95,
    "latest_pre_kickoff_source": "TAB pre-game check 14 min before game time",
    "estimated_qi": 95,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  },
  {
    "bet_id": "d74d155c74e794e7",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:43:37.084Z",
    "opening_odds": 2.35,
    "opening_model_price": 2.02,
    "opening_ev": 16.34,
    "opening_qi": 73,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 2.2,
    "estimated_clv_percent": 6.82,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "current_odds": 2.2,
    "current_model_price": 1.7,
    "current_ev": 29.41,
    "current_qi": 92,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "latest_pre_kickoff_odds": 2.2,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "TAB",
    "latest_pre_kickoff_clv_percent": 6.82,
    "latest_pre_kickoff_qi": 92,
    "latest_pre_kickoff_source": "TAB pre-game check 14 min before game time",
    "estimated_qi": 92,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  },
  {
    "bet_id": "55a69dc3ef21ec96",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 4.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T00:44:14.514Z",
    "opening_odds": 1.2,
    "opening_model_price": 1.14,
    "opening_ev": 5.26,
    "opening_qi": 74,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 1.18,
    "estimated_clv_percent": 1.69,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "current_odds": 1.18,
    "current_model_price": 1.09,
    "current_ev": 8.26,
    "current_qi": 84,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "latest_pre_kickoff_odds": 1.18,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "TAB",
    "latest_pre_kickoff_clv_percent": 1.69,
    "latest_pre_kickoff_qi": 84,
    "latest_pre_kickoff_source": "TAB pre-game check 14 min before game time",
    "estimated_qi": 84,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  },
  {
    "bet_id": "a1064cbd7c266cca",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Main Match",
    "target_selection": "Iraq or Draw",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-15T23:47:57.621Z",
    "opening_odds": 4.75,
    "opening_model_price": 2.86,
    "opening_ev": 66.08,
    "opening_qi": 77,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": 3.9,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "TAB",
    "latest_pre_kickoff_clv_percent": 21.79,
    "latest_pre_kickoff_qi": 83,
    "latest_pre_kickoff_source": "TAB pre-game check 14 min before game time",
    "estimated_closing_odds": 3.9,
    "estimated_clv_percent": 21.79,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "estimated_qi": 83,
    "current_odds": 3.9,
    "current_model_price": 2.59,
    "current_ev": 50.58,
    "current_qi": 83,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  },
  {
    "bet_id": "dc2627d3300ea896",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Main Match",
    "target_selection": "Iraq or Draw",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-15T05:25:04.454Z",
    "opening_odds": 5,
    "opening_model_price": 3.3,
    "opening_ev": 51.52,
    "opening_qi": 70,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 4.5,
    "estimated_clv_percent": 11.11,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "current_odds": 4.5,
    "current_model_price": 2.59,
    "current_ev": 73.75,
    "current_qi": 79,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "latest_pre_kickoff_odds": 4.5,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "SportsBet",
    "latest_pre_kickoff_clv_percent": 11.11,
    "latest_pre_kickoff_qi": 79,
    "latest_pre_kickoff_source": "SportsBet pre-game check 14 min before game time",
    "estimated_qi": 79,
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "SportsBet price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  },
  {
    "bet_id": "503ee37a0138e3f5",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-16T00:08:07.183Z",
    "opening_odds": 4.8,
    "opening_model_price": 3.15,
    "opening_ev": 52.38,
    "opening_qi": 72,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "latest_pre_kickoff_odds": 4.5,
    "latest_pre_kickoff_at": "2026-06-16T21:46:00.771Z",
    "latest_pre_kickoff_bookie": "TAB",
    "latest_pre_kickoff_clv_percent": 6.67,
    "latest_pre_kickoff_qi": 71,
    "latest_pre_kickoff_source": "TAB pre-game check 14 min before game time",
    "estimated_closing_odds": 4.5,
    "estimated_clv_percent": 6.67,
    "estimated_closing_source": "Estimated from nearest saved price; previous closing capture was outside the final 5-minute window.",
    "result_status": "lost",
    "result_detail": "FIFA final: Iraq 1-4 Norway.",
    "settlement_source": "https://www.fifatrainingcentre.com/media/native/tournaments/fifa-world-cup/2026/PMSR-M18-IRQ-V-NOR.pdf",
    "estimated_qi": 71,
    "current_odds": 4.5,
    "current_model_price": 3.08,
    "current_ev": 46.1,
    "current_qi": 71,
    "last_seen_at": "2026-06-17T11:24:15.383Z",
    "closing_qi": null,
    "closing_bookie": null,
    "closing_source": "No Betfair/Pinnacle close captured around 5 minutes before game time",
    "closing_status": "latest_pre_kickoff_estimate",
    "save_rule": "Saved immediately when the selection first cleared QI 70+ before kickoff.",
    "opening_source": "TAB price when the agent first saved the qualified selection.",
    "clv_benchmark_rule": "Official CLV uses Betfair or Pinnacle around 5 minutes before game time; soft-book closes are estimates only.",
    "closing_reference_type": "latest_estimate",
    "settled_at": "2026-06-17T01:42:32.702Z"
  }
];
