window.embeddedBetHistory = [
  {
    "bet_id": "cc1e28177ba74e5f",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 4.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.68,
    "opening_model_price": 1.44,
    "opening_ev": 16.67,
    "opening_qi": 92,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.72,
    "current_model_price": 1.44,
    "current_ev": 19.44,
    "current_qi": 96,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "b411cf9111c590a4",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.8,
    "opening_model_price": 1.87,
    "opening_ev": 49.73,
    "opening_qi": 97,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.8,
    "current_model_price": 1.87,
    "current_ev": 49.73,
    "current_qi": 90,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "567c6536be9278a2",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.63,
    "opening_model_price": 1.87,
    "opening_ev": 40.64,
    "opening_qi": 96,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.63,
    "current_model_price": 1.87,
    "current_ev": 40.64,
    "current_qi": 90,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "b1cfa71072ad4f14",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Under 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.5,
    "opening_model_price": 1.98,
    "opening_ev": 26.26,
    "opening_qi": 93,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.5,
    "current_model_price": 1.98,
    "current_ev": 26.26,
    "current_qi": 84,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "cc6876fecfeaf719",
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "Sportsbet / PointsBet",
    "first_seen_at": "2026-06-14T09:03:32.471Z",
    "opening_odds": 21,
    "opening_model_price": 14.49,
    "opening_ev": 44.93,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 21,
    "current_model_price": 14.49,
    "current_ev": 44.93,
    "current_qi": 38,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "ecdf14cc0d8d6cd8",
    "match_name": "Ivory Coast vs Ecuador",
    "kickoff_time_aest": "2026-06-15T09:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.62,
    "opening_model_price": 1.39,
    "opening_ev": 16.55,
    "opening_qi": 92,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.6,
    "current_model_price": 1.39,
    "current_ev": 15.11,
    "current_qi": 90,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "580b85ad7affe4cf",
    "match_name": "Ivory Coast vs Ecuador",
    "kickoff_time_aest": "2026-06-15T09:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.8,
    "opening_model_price": 2.16,
    "opening_ev": 29.63,
    "opening_qi": 92,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.8,
    "current_model_price": 2.16,
    "current_ev": 29.63,
    "current_qi": 82,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "5ed8a005004133b3",
    "match_name": "Ivory Coast vs Ecuador",
    "kickoff_time_aest": "2026-06-15T09:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.3,
    "opening_model_price": 1.96,
    "opening_ev": 17.35,
    "opening_qi": 88,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.25,
    "current_model_price": 1.96,
    "current_ev": 14.8,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "616d1ffe989d4c9f",
    "match_name": "Sweden vs Tunisia",
    "kickoff_time_aest": "2026-06-15T12:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.15,
    "opening_model_price": 1.9,
    "opening_ev": 13.16,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.1,
    "current_model_price": 1.9,
    "current_ev": 10.53,
    "current_qi": 71,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "849845aafc846fae",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.75,
    "opening_model_price": 1.87,
    "opening_ev": 47.06,
    "opening_qi": 98,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.75,
    "current_model_price": 1.87,
    "current_ev": 47.06,
    "current_qi": 90,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "769aeb477bc47424",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.6,
    "opening_model_price": 1.87,
    "opening_ev": 39.04,
    "opening_qi": 96,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.5,
    "current_model_price": 1.87,
    "current_ev": 33.69,
    "current_qi": 89,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "cb0529d26ebe1a93",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 13,
    "opening_model_price": 10.82,
    "opening_ev": 20.15,
    "opening_qi": 80,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 12,
    "current_model_price": 10.82,
    "current_ev": 10.91,
    "current_qi": 32,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null
  },
  {
    "bet_id": "6c840404fb575384",
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Cape Verde to Win",
    "au_bookie": "Sportsbet / TAB",
    "first_seen_at": "2026-06-13T16:45:59.182Z",
    "opening_odds": 26,
    "opening_model_price": 24.71,
    "opening_ev": 5.22,
    "opening_qi": 70,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 26,
    "current_model_price": 24.71,
    "current_ev": 5.22,
    "current_qi": 28,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "7e62122b67966bd8",
    "match_name": "Saudi Arabia vs Uruguay",
    "kickoff_time_aest": "2026-06-16T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.67,
    "opening_ev": 16.77,
    "opening_qi": 90,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.95,
    "current_model_price": 1.67,
    "current_ev": 16.77,
    "current_qi": 86,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "346abbabbda5faab",
    "match_name": "Saudi Arabia vs Uruguay",
    "kickoff_time_aest": "2026-06-16T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.3,
    "opening_model_price": 1.23,
    "opening_ev": 5.69,
    "opening_qi": 80,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.3,
    "current_model_price": 1.23,
    "current_ev": 5.69,
    "current_qi": 74,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "af0ced9d3ce47d92",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.46,
    "opening_model_price": 1.3,
    "opening_ev": 12.31,
    "opening_qi": 90,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.46,
    "current_model_price": 1.3,
    "current_ev": 12.31,
    "current_qi": 88,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "02c39f5901f181c2",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.35,
    "opening_model_price": 1.88,
    "opening_ev": 25,
    "opening_qi": 93,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.35,
    "current_model_price": 1.88,
    "current_ev": 25,
    "current_qi": 85,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "bb677a9c5d1e9309",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.15,
    "opening_model_price": 1.89,
    "opening_ev": 13.76,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.15,
    "current_model_price": 1.89,
    "current_ev": 13.76,
    "current_qi": 76,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "6ecc09ef5590e849",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Chris Wood: Anytime Goal",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-14T03:57:56.927Z",
    "opening_odds": 4.2,
    "opening_model_price": 2.93,
    "opening_ev": 43.34,
    "opening_qi": 94,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 4.2,
    "current_model_price": 2.93,
    "current_ev": 43.34,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "6910eacb2990f872",
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.1,
    "opening_model_price": 1.89,
    "opening_ev": 11.11,
    "opening_qi": 84,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.1,
    "current_model_price": 1.89,
    "current_ev": 11.11,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "eb57d398ee780b1f",
    "match_name": "France vs Senegal",
    "kickoff_time_aest": "2026-06-17T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.87,
    "opening_model_price": 1.68,
    "opening_ev": 11.31,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.87,
    "current_model_price": 1.68,
    "current_ev": 11.31,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "6465e7c0ffc946bd",
    "match_name": "France vs Senegal",
    "kickoff_time_aest": "2026-06-17T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.3,
    "opening_model_price": 1.23,
    "opening_ev": 5.69,
    "opening_qi": 80,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.3,
    "current_model_price": 1.23,
    "current_ev": 5.69,
    "current_qi": 74,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "448b83bf094c4a8e",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.5,
    "opening_model_price": 1.98,
    "opening_ev": 26.26,
    "opening_qi": 93,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.5,
    "current_model_price": 1.98,
    "current_ev": 26.26,
    "current_qi": 84,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "8c3bb8cbb804d53e",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.35,
    "opening_model_price": 1.98,
    "opening_ev": 18.69,
    "opening_qi": 89,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.35,
    "current_model_price": 1.98,
    "current_ev": 18.69,
    "current_qi": 76,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "b114f0ebb9d235ab",
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Iraq to Win",
    "au_bookie": "PointsBet / Sportsbet",
    "first_seen_at": "2026-06-14T09:03:32.471Z",
    "opening_odds": 15,
    "opening_model_price": 14.14,
    "opening_ev": 6.08,
    "opening_qi": 72,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 15,
    "current_model_price": 14.14,
    "current_ev": 6.08,
    "current_qi": 29,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "de205448bd845adf",
    "match_name": "Argentina vs Algeria",
    "kickoff_time_aest": "2026-06-17T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.64,
    "opening_ev": 18.9,
    "opening_qi": 91,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.95,
    "current_model_price": 1.64,
    "current_ev": 18.9,
    "current_qi": 89,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "de1336d9b2a0d00f",
    "match_name": "Argentina vs Algeria",
    "kickoff_time_aest": "2026-06-17T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.3,
    "opening_model_price": 1.22,
    "opening_ev": 6.56,
    "opening_qi": 83,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.3,
    "current_model_price": 1.22,
    "current_ev": 6.56,
    "current_qi": 77,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "36aba8d84703c3f4",
    "match_name": "Argentina vs Algeria",
    "kickoff_time_aest": "2026-06-17T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 3.3,
    "opening_model_price": 2.58,
    "opening_ev": 27.91,
    "opening_qi": 91,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 3.3,
    "current_model_price": 2.58,
    "current_ev": 27.91,
    "current_qi": 73,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "d8586306cfe152d6",
    "match_name": "Austria vs Jordan",
    "kickoff_time_aest": "2026-06-17T14:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.68,
    "opening_model_price": 1.58,
    "opening_ev": 6.33,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.68,
    "current_model_price": 1.58,
    "current_ev": 6.33,
    "current_qi": 71,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "a02182554b1dddbe",
    "match_name": "Portugal vs DR Congo",
    "kickoff_time_aest": "2026-06-18T03:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.72,
    "opening_model_price": 1.57,
    "opening_ev": 9.55,
    "opening_qi": 84,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.72,
    "current_model_price": 1.57,
    "current_ev": 9.55,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "52454c3cb6713b0f",
    "match_name": "England vs Croatia",
    "kickoff_time_aest": "2026-06-18T06:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.15,
    "opening_model_price": 1.82,
    "opening_ev": 18.13,
    "opening_qi": 90,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.15,
    "current_model_price": 1.82,
    "current_ev": 18.13,
    "current_qi": 83,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "885bba18cf02a073",
    "match_name": "England vs Croatia",
    "kickoff_time_aest": "2026-06-18T06:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.38,
    "opening_model_price": 1.28,
    "opening_ev": 7.81,
    "opening_qi": 84,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.38,
    "current_model_price": 1.28,
    "current_ev": 7.81,
    "current_qi": 79,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "1e5664836c7c3bcb",
    "match_name": "Ghana vs Panama",
    "kickoff_time_aest": "2026-06-18T09:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.44,
    "opening_model_price": 1.33,
    "opening_ev": 8.27,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.44,
    "current_model_price": 1.33,
    "current_ev": 8.27,
    "current_qi": 79,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "82091f41c32216b8",
    "match_name": "Ghana vs Panama",
    "kickoff_time_aest": "2026-06-18T09:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.3,
    "opening_model_price": 1.97,
    "opening_ev": 16.75,
    "opening_qi": 88,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.3,
    "current_model_price": 1.97,
    "current_ev": 16.75,
    "current_qi": 74,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "ed4afff02b7109a1",
    "match_name": "Uzbekistan vs Colombia",
    "kickoff_time_aest": "2026-06-18T12:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.63,
    "opening_ev": 19.63,
    "opening_qi": 92,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.95,
    "current_model_price": 1.63,
    "current_ev": 19.63,
    "current_qi": 91,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "1a4598dffecc8deb",
    "match_name": "Uzbekistan vs Colombia",
    "kickoff_time_aest": "2026-06-18T12:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.3,
    "opening_model_price": 1.21,
    "opening_ev": 7.44,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.3,
    "current_model_price": 1.21,
    "current_ev": 7.44,
    "current_qi": 79,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "d913be2851615d1b",
    "match_name": "Uzbekistan vs Colombia",
    "kickoff_time_aest": "2026-06-18T12:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 3.3,
    "opening_model_price": 2.55,
    "opening_ev": 29.41,
    "opening_qi": 92,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 3.3,
    "current_model_price": 2.55,
    "current_ev": 29.41,
    "current_qi": 74,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "339d071f7d56099e",
    "match_name": "Czech Republic vs South Africa",
    "kickoff_time_aest": "2026-06-19T02:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.05,
    "opening_model_price": 1.8,
    "opening_ev": 13.89,
    "opening_qi": 87,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.05,
    "current_model_price": 1.8,
    "current_ev": 13.89,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "2021f5aac1b6b399",
    "match_name": "Czech Republic vs South Africa",
    "kickoff_time_aest": "2026-06-19T02:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.34,
    "opening_model_price": 1.27,
    "opening_ev": 5.51,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.34,
    "current_model_price": 1.27,
    "current_ev": 5.51,
    "current_qi": 73,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "ce7c72370856e1b5",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.1,
    "opening_model_price": 1.75,
    "opening_ev": 20,
    "opening_qi": 91,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.1,
    "current_model_price": 1.75,
    "current_ev": 20,
    "current_qi": 87,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "caf558fb60c28a34",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.36,
    "opening_model_price": 1.26,
    "opening_ev": 7.94,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.36,
    "current_model_price": 1.26,
    "current_ev": 7.94,
    "current_qi": 79,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "4156895f22f046fd",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.15,
    "opening_model_price": 1.93,
    "opening_ev": 11.4,
    "opening_qi": 84,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.15,
    "current_model_price": 1.93,
    "current_ev": 11.4,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "02f38cd69a33111f",
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 3.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 3.8,
    "opening_model_price": 2.89,
    "opening_ev": 31.49,
    "opening_qi": 91,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 3.8,
    "current_model_price": 2.89,
    "current_ev": 31.49,
    "current_qi": 70,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "20c1851f42468cc1",
    "match_name": "Canada vs Qatar",
    "kickoff_time_aest": "2026-06-19T08:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.75,
    "opening_model_price": 1.58,
    "opening_ev": 10.76,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.75,
    "current_model_price": 1.58,
    "current_ev": 10.76,
    "current_qi": 80,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "35065341a9dce83f",
    "match_name": "Canada vs Qatar",
    "kickoff_time_aest": "2026-06-19T08:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "SportsBet",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.5,
    "opening_model_price": 2.07,
    "opening_ev": 20.77,
    "opening_qi": 90,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.5,
    "current_model_price": 2.07,
    "current_ev": 20.77,
    "current_qi": 76,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "7472d2164ed6dbd6",
    "match_name": "Canada vs Qatar",
    "kickoff_time_aest": "2026-06-19T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T21:42:33.439Z",
    "opening_odds": 5.75,
    "opening_model_price": 5.25,
    "opening_ev": 9.52,
    "opening_qi": 78,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 5.75,
    "current_model_price": 5.25,
    "current_ev": 9.52,
    "current_qi": 38,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "c0e03e92b1c2deb8",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 1.46,
    "opening_model_price": 1.32,
    "opening_ev": 10.61,
    "opening_qi": 88,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 1.46,
    "current_model_price": 1.32,
    "current_ev": 10.61,
    "current_qi": 84,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "96a7f19ba0747777",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.35,
    "opening_model_price": 1.95,
    "opening_ev": 20.51,
    "opening_qi": 90,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.35,
    "current_model_price": 1.95,
    "current_ev": 20.51,
    "current_qi": 78,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "71d9b14cc64d4a47",
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "market_matrix": "Main Match",
    "target_selection": "BTTS Yes",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2.1,
    "opening_model_price": 1.88,
    "opening_ev": 11.7,
    "opening_qi": 85,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Awaiting final result check.",
    "settlement_source": null,
    "current_odds": 2.1,
    "current_model_price": 1.88,
    "current_ev": 11.7,
    "current_qi": 73,
    "last_seen_at": "2026-06-14T09:36:53.185Z"
  },
  {
    "bet_id": "0cd2e7e6b50a9dfa",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Omar Alderete: To Get Carded",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 3.76,
    "opening_model_price": 2.6,
    "opening_ev": 44.62,
    "opening_qi": 95,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 3.76,
    "current_model_price": 2.6,
    "current_ev": 44.62,
    "current_qi": 82,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 3.76,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "60f23ca7387fc316",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "USA to Win",
    "au_bookie": "Neds",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 2,
    "opening_model_price": 1.78,
    "opening_ev": 12.36,
    "opening_qi": 86,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 2,
    "current_model_price": 1.78,
    "current_ev": 12.36,
    "current_qi": 77,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 2,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "c7bab8ab5c37ec1e",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Spread",
    "target_selection": "USA -0.5",
    "au_bookie": "Ladbrokes",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.95,
    "opening_model_price": 1.78,
    "opening_ev": 9.55,
    "opening_qi": 83,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 1.95,
    "current_model_price": 1.78,
    "current_ev": 9.55,
    "current_qi": 72,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 1.95,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "0f3625818db9b60f",
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "market_matrix": "Exact Score",
    "target_selection": "USA 1-0",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 6.5,
    "opening_model_price": 5.8,
    "opening_ev": 12.07,
    "opening_qi": 79,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "current_odds": 6.5,
    "current_model_price": 5.8,
    "current_ev": 12.07,
    "current_qi": 39,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "closing_status": "missing_fresh_close",
    "estimated_closing_odds": 6.5,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: United States 4-1 Paraguay.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760417/paraguay-united-states",
    "settled_at": "2026-06-13T10:35:36.571Z"
  },
  {
    "bet_id": "6c00d0a6d298095a",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T20:56:09.020Z",
    "opening_odds": 21,
    "opening_model_price": 6.47,
    "opening_ev": 224.57,
    "opening_qi": 99,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 21,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 21,
    "current_model_price": 6.47,
    "current_ev": 224.57,
    "current_qi": 64,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "af3321b011cd184b",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Qatar to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-13T19:47:54.872Z",
    "opening_odds": 91,
    "opening_model_price": 14.66,
    "opening_ev": 520.74,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 251,
    "estimated_clv_percent": -63.75,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 251,
    "current_model_price": 14.66,
    "current_ev": 1612.14,
    "current_qi": 54,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "1b6e90811728cb18",
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "Sportsbet / PointsBet",
    "first_seen_at": "2026-06-13T15:10:30.583Z",
    "opening_odds": 7,
    "opening_model_price": 6.47,
    "opening_ev": 8.19,
    "opening_qi": 76,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 7,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: Qatar 1-1 Switzerland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760420/switzerland-qatar",
    "current_odds": 7,
    "current_model_price": 6.47,
    "current_ev": 8.19,
    "current_qi": 36,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-13T22:15:27.852Z"
  },
  {
    "bet_id": "1053824585cb3671",
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "Brazil to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.48,
    "opening_model_price": 1.42,
    "opening_ev": 4.23,
    "opening_qi": 73,
    "closing_odds": 1.69,
    "closing_captured_at": "2026-06-13T21:42:31.932Z",
    "clv_percent": -12.43,
    "current_odds": 31,
    "current_model_price": 1.42,
    "current_ev": 2083.1,
    "current_qi": 88,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "result_status": "lost",
    "result_detail": "ESPN final: Brazil 1-1 Morocco.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760419/morocco-brazil",
    "closing_source": "Confirmed live check 17 min before kickoff",
    "closing_status": "confirmed",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "settled_at": "2026-06-14T01:02:30.916Z"
  },
  {
    "bet_id": "e57f1fc9ba28e787",
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Morocco to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-14T00:12:23.782Z",
    "opening_odds": 21,
    "opening_model_price": 5.76,
    "opening_ev": 264.58,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 21,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Brazil 1-1 Morocco.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760419/morocco-brazil",
    "current_odds": 21,
    "current_model_price": 5.76,
    "current_ev": 264.58,
    "current_qi": 68,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T01:02:30.916Z"
  },
  {
    "bet_id": "5cb28768b798afca",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Match to end in a Draw",
    "au_bookie": "PointsBet / TAB",
    "first_seen_at": "2026-06-14T03:05:16.102Z",
    "opening_odds": 21,
    "opening_model_price": 4.33,
    "opening_ev": 384.99,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 21,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Haiti 0-1 Scotland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760418/scotland-haiti",
    "current_odds": 21,
    "current_model_price": 4.33,
    "current_ev": 384.99,
    "current_qi": 69,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T04:11:26.146Z"
  },
  {
    "bet_id": "30cfe8c9768786fa",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Haiti to Win",
    "au_bookie": "PointsBet / TAB",
    "first_seen_at": "2026-06-14T02:41:59.248Z",
    "opening_odds": 26,
    "opening_model_price": 5.9,
    "opening_ev": 340.68,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 26,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Haiti 0-1 Scotland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760418/scotland-haiti",
    "current_odds": 26,
    "current_model_price": 5.9,
    "current_ev": 340.68,
    "current_qi": 68,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T04:11:26.146Z"
  },
  {
    "bet_id": "e6a2acee4c7ca32a",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Haiti to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-14T03:05:16.102Z",
    "opening_odds": 351,
    "opening_model_price": 5.9,
    "opening_ev": 5849.15,
    "opening_qi": 100,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 351,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "lost",
    "result_detail": "ESPN final: Haiti 0-1 Scotland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760418/scotland-haiti",
    "current_odds": 351,
    "current_model_price": 5.9,
    "current_ev": 5849.15,
    "current_qi": 68,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T04:11:26.146Z"
  },
  {
    "bet_id": "8a8009156f469471",
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "market_matrix": "Moneyline",
    "target_selection": "Scotland to Win",
    "au_bookie": "PointsBet",
    "first_seen_at": "2026-06-12T13:34:51.251Z",
    "opening_odds": 1.75,
    "opening_model_price": 1.65,
    "opening_ev": 6.06,
    "opening_qi": 78,
    "closing_odds": 1.53,
    "closing_captured_at": "2026-06-14T00:31:11.998Z",
    "clv_percent": 14.38,
    "current_odds": 1.01,
    "current_model_price": 1.65,
    "current_ev": -38.79,
    "current_qi": 33,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "result_status": "won",
    "result_detail": "ESPN final: Haiti 0-1 Scotland.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760418/scotland-haiti",
    "closing_source": "Confirmed live check 29 min before kickoff",
    "closing_status": "confirmed",
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "settled_at": "2026-06-14T04:11:26.146Z"
  },
  {
    "bet_id": "da44492578a009a0",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Arda Güler: Goal or Assist",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-14T03:57:56.927Z",
    "opening_odds": 2,
    "opening_model_price": 1.72,
    "opening_ev": 16.28,
    "opening_qi": 89,
    "closing_odds": 2,
    "closing_captured_at": "2026-06-14T03:57:12.279Z",
    "clv_percent": 0,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Final score verified: Australia 2-0 Türkiye. This market needs a more detailed settlement feed.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 2,
    "current_model_price": 1.72,
    "current_ev": 16.28,
    "current_qi": 83,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "Confirmed live check 3 min before kickoff",
    "closing_status": "confirmed"
  },
  {
    "bet_id": "9c4101f1dfcfc213",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 2.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 2,
    "opening_model_price": 1.81,
    "opening_ev": 10.5,
    "opening_qi": 84,
    "closing_odds": 2.1,
    "closing_captured_at": "2026-06-14T03:56:08.383Z",
    "clv_percent": -4.76,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Final score verified: Australia 2-0 Türkiye. This market needs a more detailed settlement feed.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 2.1,
    "current_model_price": 1.81,
    "current_ev": 16.02,
    "current_qi": 81,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "Confirmed live check 4 min before kickoff",
    "closing_status": "confirmed"
  },
  {
    "bet_id": "0312c6b5a421712a",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Player Prop",
    "target_selection": "Harry Souttar: To Get Carded",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-14T03:57:56.927Z",
    "opening_odds": 5,
    "opening_model_price": 3.3,
    "opening_ev": 51.52,
    "opening_qi": 94,
    "closing_odds": 5,
    "closing_captured_at": "2026-06-14T03:57:12.279Z",
    "clv_percent": 0,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "lost",
    "result_detail": "ESPN final: Australia 2-0 Türkiye.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 5,
    "current_model_price": 3.3,
    "current_ev": 51.52,
    "current_qi": 70,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "Confirmed live check 3 min before kickoff",
    "closing_status": "confirmed",
    "settled_at": "2026-06-14T08:30:09.686Z"
  },
  {
    "bet_id": "b3d20f997ef879ea",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Goal Totals",
    "target_selection": "Over 1.5 Goals",
    "au_bookie": "TAB",
    "first_seen_at": "2026-06-14T03:56:49.425Z",
    "opening_odds": 1.34,
    "opening_model_price": 1.28,
    "opening_ev": 4.69,
    "opening_qi": 76,
    "closing_odds": 1.34,
    "closing_captured_at": "2026-06-14T03:56:08.383Z",
    "clv_percent": 0,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "pending",
    "result_detail": "Final score verified: Australia 2-0 Türkiye. This market needs a more detailed settlement feed.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 1.34,
    "current_model_price": 1.28,
    "current_ev": 4.69,
    "current_qi": 70,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "Confirmed live check 4 min before kickoff",
    "closing_status": "confirmed"
  },
  {
    "bet_id": "02737877965024df",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Australia to Win",
    "au_bookie": "Sportsbet / TAB",
    "first_seen_at": "2026-06-14T03:55:39.232Z",
    "opening_odds": 6,
    "opening_model_price": 5.48,
    "opening_ev": 9.49,
    "opening_qi": 78,
    "closing_odds": 6,
    "closing_captured_at": "2026-06-14T03:55:30.965Z",
    "clv_percent": 0,
    "estimated_closing_odds": null,
    "estimated_clv_percent": null,
    "estimated_closing_source": null,
    "result_status": "won",
    "result_detail": "ESPN final: Australia 2-0 Türkiye.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 6,
    "current_model_price": 5.48,
    "current_ev": 9.49,
    "current_qi": 38,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_source": "Confirmed live check 4 min before kickoff",
    "closing_status": "confirmed",
    "settled_at": "2026-06-14T08:30:09.686Z"
  },
  {
    "bet_id": "97b1f60c6341a286",
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "market_matrix": "Full Match Model",
    "target_selection": "Australia to Win",
    "au_bookie": "Sportsbet",
    "first_seen_at": "2026-06-14T04:11:26.146Z",
    "opening_odds": 6,
    "opening_model_price": 5.48,
    "opening_ev": 9.49,
    "opening_qi": 78,
    "closing_odds": null,
    "closing_captured_at": null,
    "clv_percent": null,
    "estimated_closing_odds": 6,
    "estimated_clv_percent": 0,
    "estimated_closing_source": "Estimated from nearest saved price; not an official closing line.",
    "result_status": "won",
    "result_detail": "ESPN final: Australia 2-0 Türkiye.",
    "settlement_source": "https://www.espn.com/soccer/match/_/gameId/760421/turkiye-australia",
    "current_odds": 6,
    "current_model_price": 5.48,
    "current_ev": 9.49,
    "current_qi": 38,
    "last_seen_at": "2026-06-14T09:36:53.185Z",
    "closing_status": "missing_fresh_close",
    "closing_source": "No confirmed live check in the final 30 minutes before kickoff",
    "settled_at": "2026-06-14T08:30:09.686Z"
  }
];
