window.embeddedDataset = [
  {
    "match_name": "Canada vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-13T05:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Facundo Tello (Argentina)",
    "referee_tendencies": "Verified ref: Facundo Tello is expected to manage time-wasting firmly. That slightly helps bets linked to delays, discipline, and late-game control, but it does not create a standalone card edge.",
    "tactical_summary": "Canada bring direct wide running and fast attacks into space, while Bosnia & Herzegovina bring slower possession and physical central duels. The full match model rates Canada as the most likely winner at about 52.1%, with the draw around 27.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Canada to Win",
        "true_price": 1.92,
        "current_odds": 1.75,
        "au_bookie": "Sportsbet"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.68,
        "current_odds": 3.5,
        "au_bookie": "Sportsbet"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Bosnia & Herzegovina to Win",
        "true_price": 4.82,
        "current_odds": 4.75,
        "au_bookie": "Sportsbet"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Canada to Win",
        "true_price": 1.92,
        "current_odds": 1.8,
        "au_bookie": "TAB"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.68,
        "current_odds": 3.5,
        "au_bookie": "TAB"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Bosnia & Herzegovina to Win",
        "true_price": 4.82,
        "current_odds": 4.5,
        "au_bookie": "TAB"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Canada to Win",
        "true_price": 1.92,
        "current_odds": 1.8,
        "au_bookie": "Neds"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.68,
        "current_odds": 3.5,
        "au_bookie": "Neds"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Bosnia & Herzegovina to Win",
        "true_price": 4.82,
        "current_odds": 4.5,
        "au_bookie": "Neds"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Canada to Win",
        "true_price": 1.92,
        "current_odds": 1.84,
        "au_bookie": "BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.68,
        "current_odds": 3.3,
        "au_bookie": "BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Bosnia & Herzegovina to Win",
        "true_price": 4.82,
        "current_odds": 4.3,
        "au_bookie": "BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "verified",
    "referee_source": "Post-match report names Facundo Tello as referee; FIFA official roster confirms Tello is a 2026 World Cup referee.",
    "referee_source_url": "https://www.thesun.co.uk/sport/39394650/world-cup-rule-canada-bosnia-throw-in/",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "No matching Odds API event found."
  },
  {
    "match_name": "USA vs Paraguay",
    "kickoff_time_aest": "2026-06-13T11:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Danny Makkelie (Netherlands)",
    "referee_tendencies": "Verified ref: Danny Makkelie usually punishes tactical fouls and cynical stops quickly. That supports the card-risk angle for Paraguay defenders if USA keep attacking in transition.",
    "tactical_summary": "USA bring high-tempo pressing and wide overloads, while Paraguay bring compact defending and counter-attacking phases. The full match model rates USA as the most likely winner at about 45.5%, with the draw around 29.9%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Player Prop",
        "target_selection": "Omar Alderete: To Get Carded",
        "true_price": 2.6,
        "current_odds": 3.76,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "unsupported_by_oddsapi",
        "odds_refresh_note": "Odds API standard soccer feed does not cover this market type."
      },
      {
        "market_matrix": "Exact Score",
        "target_selection": "USA 1-0",
        "true_price": 5.8,
        "current_odds": 6.5,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "unsupported_by_oddsapi",
        "odds_refresh_note": "Odds API standard soccer feed does not cover this market type."
      },
      {
        "market_matrix": "Moneyline",
        "target_selection": "USA to Win",
        "true_price": 1.78,
        "current_odds": 2,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Neds was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Spread",
        "target_selection": "USA -0.5",
        "true_price": 1.78,
        "current_odds": 1.95,
        "au_bookie": "Ladbrokes",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Ladbrokes was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "USA to Win",
        "true_price": 2.2,
        "current_odds": 2.05,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Sportsbet was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.34,
        "current_odds": 3.1,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Sportsbet was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Paraguay to Win",
        "true_price": 4.06,
        "current_odds": 4,
        "au_bookie": "Sportsbet",
        "previous_odds": 3.9,
        "odds_updated_at": "2026-06-12T23:03:17.291Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Sportsbet was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "USA to Win",
        "true_price": 2.2,
        "current_odds": 2.1,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "TAB was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.34,
        "current_odds": 3.2,
        "au_bookie": "TAB",
        "bad_odds_removed": 17,
        "odds_updated_at": "2026-06-13T01:55:34.076Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Bad outlier removed; using latest recorded TAB price before kickoff."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Paraguay to Win",
        "true_price": 4.06,
        "current_odds": 4,
        "au_bookie": "TAB",
        "bad_odds_removed": 51,
        "odds_updated_at": "2026-06-13T01:55:34.076Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Bad outlier removed; using latest recorded TAB price before kickoff."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "USA to Win",
        "true_price": 2.2,
        "current_odds": 2.05,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Neds was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.34,
        "current_odds": 3.2,
        "au_bookie": "Neds",
        "previous_odds": 3.15,
        "odds_updated_at": "2026-06-13T00:49:01.961Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Neds was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Paraguay to Win",
        "true_price": 4.06,
        "current_odds": 3.9,
        "au_bookie": "Neds",
        "previous_odds": 3.8,
        "odds_updated_at": "2026-06-12T23:03:17.291Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Neds was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "USA to Win",
        "true_price": 2.2,
        "current_odds": 2.05,
        "au_bookie": "BetRight",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "BetRight was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.34,
        "current_odds": 3.15,
        "au_bookie": "BetRight",
        "previous_odds": 3.1,
        "odds_updated_at": "2026-06-13T00:49:01.961Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "BetRight was not present in the matched Odds API event."
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Paraguay to Win",
        "true_price": 4.06,
        "current_odds": 3.65,
        "au_bookie": "BetRight",
        "previous_odds": 3.7,
        "odds_updated_at": "2026-06-13T00:49:01.961Z",
        "odds_checked_at": "2026-06-13T02:30:14.308Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "BetRight was not present in the matched Odds API event."
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "verified",
    "referee_source": "Current USA-Paraguay referee report names Danny Makkelie, with Hessel Steegstra and Jan De Vries as assistants.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "No matching Odds API event found.",
    "referee_source_url": "https://www.sbnation.com/soccer/24481331/usmnt-vs-paraguay-referees-2026-world-cup-danny-makkelie-hessel-steegstra-jan-de-vries"
  },
  {
    "match_name": "Qatar vs Switzerland",
    "kickoff_time_aest": "2026-06-14T05:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Mustapha Ghorbal (Algeria)",
    "referee_tendencies": "Mustapha Ghorbal (Algeria) is listed in the model notes, but not independently verified yet. Treat any referee angle as a watch item, not a betting edge.",
    "tactical_summary": "Qatar bring deep defensive blocks and low-risk possession, while Switzerland bring controlled midfield tempo and disciplined structure. The full match model rates Switzerland as the most likely winner at about 77.5%, with the draw around 15.5%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Switzerland to Win",
        "true_price": 1.29,
        "current_odds": 1.2,
        "au_bookie": "Neds / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T17:59:27.010Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Neds / BetRight was not present in the matched Odds API event.",
        "best_price_tied_books": "Neds / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Qatar to Win",
        "true_price": 14.66,
        "current_odds": 15,
        "au_bookie": "Sportsbet / PointsBet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T17:59:27.010Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Sportsbet / PointsBet / TAB was not present in the matched Odds API event.",
        "best_price_tied_books": "Sportsbet / PointsBet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 6.47,
        "current_odds": 7,
        "au_bookie": "Sportsbet / PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T17:59:27.010Z",
        "odds_refresh_status": "bookmaker_missing",
        "odds_refresh_note": "Sportsbet / PointsBet was not present in the matched Odds API event.",
        "best_price_tied_books": "Sportsbet / PointsBet",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Qatar to Win",
        "true_price": 14.66,
        "current_odds": 251,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "updated",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "previous_odds": 91
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Switzerland to Win",
        "true_price": 1.29,
        "current_odds": 1.01,
        "au_bookie": "PointsBet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "updated",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "PointsBet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "previous_odds": 1.02
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 6.47,
        "current_odds": 21,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "provided",
    "referee_source": "Initial model dataset; not independently verified by FIFA or ESPN yet.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 26634922d3f78c146440816023e40de8."
  },
  {
    "match_name": "Brazil vs Morocco",
    "kickoff_time_aest": "2026-06-14T08:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Clement Turpin (France)",
    "referee_tendencies": "Clement Turpin (France) is listed in the model notes, but not independently verified yet. Treat any referee angle as a watch item, not a betting edge.",
    "tactical_summary": "Brazil bring technical overloads and individual creation, while Morocco bring compact defensive spacing and fast transitions. The full match model rates Brazil as the most likely winner at about 57.8%, with the draw around 24.9%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Moneyline",
        "target_selection": "Brazil to Win",
        "true_price": 1.42,
        "current_odds": 1.67,
        "au_bookie": "PointsBet",
        "previous_odds": 1.69,
        "odds_updated_at": "2026-06-13T17:59:27.010Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Morocco to Win",
        "true_price": 5.76,
        "current_odds": 5.5,
        "au_bookie": "Sportsbet / PointsBet / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.02,
        "current_odds": 3.75,
        "au_bookie": "Neds / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Neds / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "provided",
    "referee_source": "Initial model dataset; not independently verified by FIFA or ESPN yet.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event f6c8748a16516e0998f95de14235432a."
  },
  {
    "match_name": "Haiti vs Scotland",
    "kickoff_time_aest": "2026-06-14T11:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Wilmar Roldan (Colombia)",
    "referee_tendencies": "Wilmar Roldan (Colombia) is listed in the model notes, but not independently verified yet. Treat any referee angle as a watch item, not a betting edge.",
    "tactical_summary": "Haiti bring straight-line speed and transition attacks, while Scotland bring set-piece pressure, width, and physical duels. The full match model rates Scotland as the most likely winner at about 59.9%, with the draw around 23.1%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Moneyline",
        "target_selection": "Scotland to Win",
        "true_price": 1.65,
        "current_odds": 1.53,
        "au_bookie": "PointsBet",
        "previous_odds": 1.56,
        "odds_updated_at": "2026-06-13T13:10:53.158Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Haiti to Win",
        "true_price": 5.9,
        "current_odds": 6,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T19:47:54.437Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.33,
        "current_odds": 4.5,
        "au_bookie": "Sportsbet / PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "provided",
    "referee_source": "Initial model dataset; not independently verified by FIFA or ESPN yet.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 5ae41a06735c926eeb7f74006933adce."
  },
  {
    "match_name": "Australia vs Turkiye",
    "kickoff_time_aest": "2026-06-14T14:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Jesus Valenzuela (Venezuela)",
    "referee_tendencies": "Jesus Valenzuela (Venezuela) is listed in the model notes, but not independently verified yet. Treat any referee angle as a watch item, not a betting edge.",
    "tactical_summary": "Australia bring physical defensive structure and direct transitions, while Turkiye bring technical midfield combinations and aggressive forward play. The full match model rates Turkey as the most likely winner at about 55.6%, with the draw around 26.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Turkey to Win",
        "true_price": 1.8,
        "current_odds": 1.7,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null,
        "previous_odds": 1.72,
        "odds_updated_at": "2026-06-13T19:47:54.437Z"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Australia to Win",
        "true_price": 5.48,
        "current_odds": 5.5,
        "au_bookie": "Sportsbet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.82,
        "current_odds": null,
        "au_bookie": "Model only",
        "odds_checked_at": "2026-06-13T11:30:06.923Z",
        "odds_refresh_status": "model_only",
        "odds_refresh_note": "Model-only draw price restored from full match model probability; no live book price confirmed yet."
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "provided",
    "referee_source": "Initial model dataset; not independently verified by FIFA or ESPN yet.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 564084f52cc9f1abcc18187c168a7cdc."
  },
  {
    "match_name": "Germany vs Curaçao",
    "kickoff_time_aest": "2026-06-15T03:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Germany bring territory control and sustained final-third pressure, while Curaçao bring deep defending and selective counter attacks. The full match model rates Germany as the most likely winner at about 90.1%, with the draw around 6.9%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 14.49,
        "current_odds": 21,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Germany to Win",
        "true_price": 1.11,
        "current_odds": 1.05,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T15:10:30.300Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Curaçao to Win",
        "true_price": 34.28,
        "current_odds": 41,
        "au_bookie": "PointsBet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T16:45:58.675Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "PointsBet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event d79edbd6aaeb578d33e313446b18d333."
  },
  {
    "match_name": "Netherlands vs Japan",
    "kickoff_time_aest": "2026-06-15T06:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Netherlands bring structured possession and wing progression, while Japan bring press resistance, quick rotations, and tempo shifts. The full match model rates Netherlands as the most likely winner at about 47.4%, with the draw around 27.0%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.7,
        "current_odds": 3.6,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T16:45:58.675Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Japan to Win",
        "true_price": 3.9,
        "current_odds": 3.75,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T19:47:54.437Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Netherlands to Win",
        "true_price": 2.11,
        "current_odds": 2,
        "au_bookie": "Sportsbet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 32ec06abda2398ac41501c86eb9aa376."
  },
  {
    "match_name": "Ivory Coast vs Ecuador",
    "kickoff_time_aest": "2026-06-15T09:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Ivory Coast bring athletic ball carrying and transition threat, while Ecuador bring compact shape with sharp vertical counters. The full match model rates Ecuador as the most likely winner at about 39.1%, with the draw around 33.3%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3,
        "current_odds": 2.9,
        "au_bookie": "BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T19:47:54.437Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked BetRight via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "previous_odds": 2.85
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Ecuador to Win",
        "true_price": 2.56,
        "current_odds": 2.45,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T19:47:54.437Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Ivory Coast to Win",
        "true_price": 3.63,
        "current_odds": 3.5,
        "au_bookie": "PointsBet / Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "PointsBet / Neds",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 05752bb341e197001387b64f3a06b9b2."
  },
  {
    "match_name": "Sweden vs Tunisia",
    "kickoff_time_aest": "2026-06-15T12:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Sweden bring aerial strength and measured possession, while Tunisia bring low-block defending and counter-attacks. The full match model rates Sweden as the most likely winner at about 49.8%, with the draw around 27.9%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Tunisia to Win",
        "true_price": 4.47,
        "current_odds": 4.5,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Sweden to Win",
        "true_price": 2.01,
        "current_odds": 1.9,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T17:59:27.010Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.59,
        "current_odds": 3.4,
        "au_bookie": "Sportsbet / PointsBet / Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet / Neds",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event b55f9569de3f4d731bc5537ff5ff43e4."
  },
  {
    "match_name": "Spain vs Cape Verde",
    "kickoff_time_aest": "2026-06-16T02:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Spain bring possession control and central overloads, while Cape Verde bring defensive compression and direct outlets. The full match model rates Spain as the most likely winner at about 87.0%, with the draw around 9.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 10.82,
        "current_odds": 12,
        "au_bookie": "Sportsbet",
        "previous_odds": 13,
        "odds_updated_at": "2026-06-13T15:10:30.300Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Spain to Win",
        "true_price": 1.15,
        "current_odds": 1.1,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Cape Verde to Win",
        "true_price": 24.71,
        "current_odds": 26,
        "au_bookie": "Sportsbet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event c54f00b11925751d2b62988775c6c239."
  },
  {
    "match_name": "Belgium vs Egypt",
    "kickoff_time_aest": "2026-06-16T05:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Belgium bring chance creation through advanced midfield quality, while Egypt bring counter-attacking pace and direct forward service. The full match model rates Belgium as the most likely winner at about 58.1%, with the draw around 24.6%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Egypt to Win",
        "true_price": 5.84,
        "current_odds": 5.75,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.06,
        "current_odds": 4,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event fbfb95c62003fd6d828b309f96ee1f9b."
  },
  {
    "match_name": "Saudi Arabia vs Uruguay",
    "kickoff_time_aest": "2026-06-16T08:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Saudi Arabia bring deep defensive spells and quick wide breaks, while Uruguay bring physical pressing and aggressive box entries. The full match model rates Uruguay as the most likely winner at about 65.8%, with the draw around 22.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Uruguay to Win",
        "true_price": 1.52,
        "current_odds": 1.45,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.5,
        "current_odds": 4.5,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T11:05:15.881Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Saudi Arabia to Win",
        "true_price": 8.24,
        "current_odds": 8,
        "au_bookie": "Sportsbet / PointsBet / TAB / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet / TAB / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 64b91c5f2db61c7358a4f05459e83c52."
  },
  {
    "match_name": "Iran vs New Zealand",
    "kickoff_time_aest": "2026-06-16T11:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Iran bring disciplined defensive structure and set-piece threat, while New Zealand bring aerial contests and direct attacking phases. The full match model rates Iran as the most likely winner at about 51.5%, with the draw around 27.9%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Iran to Win",
        "true_price": 1.94,
        "current_odds": 1.85,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T16:45:58.675Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "New Zealand to Win",
        "true_price": 4.84,
        "current_odds": 4.75,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T16:45:58.675Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.59,
        "current_odds": 3.4,
        "au_bookie": "Sportsbet / PointsBet / Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet / Neds",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event ec51b9c44ad5e34552f3ab53f7262813."
  },
  {
    "match_name": "France vs Senegal",
    "kickoff_time_aest": "2026-06-17T05:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "France bring elite transition speed and flexible attacking shape, while Senegal bring athletic midfield duels and counter pressure. The full match model rates France as the most likely winner at about 64.5%, with the draw around 22.4%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.47,
        "current_odds": 4.33,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "France to Win",
        "true_price": 1.55,
        "current_odds": 1.48,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Senegal to Win",
        "true_price": 7.52,
        "current_odds": 7.5,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 73a4fcd14cc9766b9b9bfd50b8ca153a."
  },
  {
    "match_name": "Iraq vs Norway",
    "kickoff_time_aest": "2026-06-17T08:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Iraq bring compact defending and low-possession counters, while Norway bring direct forward threat and crossing volume. The full match model rates Norway as the most likely winner at about 78.1%, with the draw around 14.8%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Iraq to Win",
        "true_price": 14.14,
        "current_odds": 15,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T15:10:30.300Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Norway to Win",
        "true_price": 1.28,
        "current_odds": 1.19,
        "au_bookie": "Neds / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Neds / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 6.74,
        "current_odds": 7,
        "au_bookie": "PointsBet / Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "PointsBet / Sportsbet",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 4d4f2b9b78182b557d4fbf8dcf4f4af2."
  },
  {
    "match_name": "Argentina vs Algeria",
    "kickoff_time_aest": "2026-06-17T11:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Argentina bring controlled possession and final-third patience, while Algeria bring technical wide play and transition threat. The full match model rates Argentina as the most likely winner at about 68.0%, with the draw around 21.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.72,
        "current_odds": 4.6,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Argentina to Win",
        "true_price": 1.47,
        "current_odds": 1.4,
        "au_bookie": "TAB / Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "TAB / Neds",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event f31b2ee9e1cc6f7e641467f8237eaa21."
  },
  {
    "match_name": "Austria vs Jordan",
    "kickoff_time_aest": "2026-06-17T14:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Austria bring organized pressing and quick vertical attacks, while Jordan bring defensive numbers and counter-attacking discipline. The full match model rates Austria as the most likely winner at about 70.9%, with the draw around 18.5%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 5.42,
        "current_odds": 5.5,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T15:10:30.300Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Jordan to Win",
        "true_price": 9.56,
        "current_odds": 9,
        "au_bookie": "TAB / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "TAB / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 25161cf6cf0cd9be17ae2e7e224a1f45."
  },
  {
    "match_name": "Portugal vs DR Congo",
    "kickoff_time_aest": "2026-06-18T03:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Portugal bring technical control and layered attacking rotations, while DR Congo bring physical duels and direct transition speed. The full match model rates Portugal as the most likely winner at about 73.0%, with the draw around 18.0%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 5.56,
        "current_odds": 5.6,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "DR Congo to Win",
        "true_price": 11.26,
        "current_odds": 11,
        "au_bookie": "Sportsbet / TAB / BetRight",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / TAB / BetRight",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Portugal to Win",
        "true_price": 1.37,
        "current_odds": 1.29,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 6cc871c121a1869b4612d3fb22fa9d55."
  },
  {
    "match_name": "England vs Croatia",
    "kickoff_time_aest": "2026-06-18T06:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "England bring territory control and wide chance creation, while Croatia bring midfield possession and tempo management. The full match model rates England as the most likely winner at about 54.6%, with the draw around 26.2%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "England to Win",
        "true_price": 1.83,
        "current_odds": 1.73,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.82,
        "current_odds": 3.8,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Croatia to Win",
        "true_price": 5.18,
        "current_odds": 5,
        "au_bookie": "Sportsbet / PointsBet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 689096c8cd7e2753b9fec95321943c5d."
  },
  {
    "match_name": "Ghana vs Panama",
    "kickoff_time_aest": "2026-06-18T09:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Ghana bring athletic pressing and fast counters, while Panama bring deep defending and physical disruption. The full match model rates Ghana as the most likely winner at about 44.8%, with the draw around 28.6%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Ghana to Win",
        "true_price": 2.23,
        "current_odds": 2.2,
        "au_bookie": "Sportsbet",
        "previous_odds": 2.1,
        "odds_updated_at": "2026-06-12T23:03:17.291Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Panama to Win",
        "true_price": 3.75,
        "current_odds": 3.45,
        "au_bookie": "Neds",
        "previous_odds": 3.6,
        "odds_updated_at": "2026-06-12T23:03:17.291Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.5,
        "current_odds": 3.4,
        "au_bookie": "PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T10:20:00.097Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 87afdb85c977b451e1c00f5e3e632601."
  },
  {
    "match_name": "Uzbekistan vs Colombia",
    "kickoff_time_aest": "2026-06-18T12:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Uzbekistan bring compact midfield shape and transition outlets, while Colombia bring front-foot pressure and wide attacking threat. The full match model rates Colombia as the most likely winner at about 69.0%, with the draw around 20.7%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Uzbekistan to Win",
        "true_price": 9.44,
        "current_odds": 9.5,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Colombia to Win",
        "true_price": 1.45,
        "current_odds": 1.38,
        "au_bookie": "TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked TAB via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.84,
        "current_odds": 4.8,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 22083e7a8e5362c711bc05c1e1319a1f."
  },
  {
    "match_name": "Czech Republic vs South Africa",
    "kickoff_time_aest": "2026-06-19T02:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Czech Republic bring structured defending and aerial pressure, while South Africa bring pace in wide areas and counters. The full match model rates Czech Republic as the most likely winner at about 55.9%, with the draw around 25.4%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.93,
        "current_odds": 3.75,
        "au_bookie": "Sportsbet",
        "previous_odds": 3.8,
        "odds_updated_at": "2026-06-12T23:03:17.291Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Czech Republic to Win",
        "true_price": 1.79,
        "current_odds": 1.8,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T13:10:53.158Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "South Africa to Win",
        "true_price": 5.39,
        "current_odds": 4.75,
        "au_bookie": "PointsBet / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked PointsBet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "PointsBet / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 66ebb9e3f949caded535d97ce686ca09."
  },
  {
    "match_name": "Switzerland vs Bosnia & Herzegovina",
    "kickoff_time_aest": "2026-06-19T05:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Switzerland bring controlled midfield tempo and disciplined structure, while Bosnia & Herzegovina bring slower possession and physical central duels. The full match model rates Switzerland as the most likely winner at about 59.2%, with the draw around 24.4%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Switzerland to Win",
        "true_price": 1.69,
        "current_odds": 1.6,
        "au_bookie": "Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Bosnia & Herzegovina to Win",
        "true_price": 6.12,
        "current_odds": 6,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 4.09,
        "current_odds": 4,
        "au_bookie": "Sportsbet / PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 289bc2e9f5adad8ae4d9a75a7c5461ad."
  },
  {
    "match_name": "Canada vs Qatar",
    "kickoff_time_aest": "2026-06-19T08:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Canada bring direct wide running and fast attacks into space, while Qatar bring deep defensive blocks and low-risk possession. The full match model rates Canada as the most likely winner at about 72.5%, with the draw around 19.0%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 5.25,
        "current_odds": 6,
        "au_bookie": "Sportsbet",
        "previous_odds": 5.5,
        "odds_updated_at": "2026-06-13T19:47:54.437Z",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight",
        "best_price_tied_books": null
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Canada to Win",
        "true_price": 1.38,
        "current_odds": 1.25,
        "au_bookie": "BetRight / PointsBet / Neds",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked BetRight via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "BetRight / PointsBet / Neds",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event fa9502285b257b03e62968d50d9229fc."
  },
  {
    "match_name": "Mexico vs South Korea",
    "kickoff_time_aest": "2026-06-19T11:00:00",
    "pitch_type": "No clear pitch edge",
    "pitch_constraints": "No reliable pitch advantage confirmed. The model is mainly using team strength, draw risk, and current bookmaker prices.",
    "referee_name": "Referee not verified",
    "referee_tendencies": "No referee-specific adjustment applied; card and foul effects are not being overclaimed.",
    "tactical_summary": "Mexico bring aggressive possession and attacking width, while South Korea bring high work-rate pressing and fast transitions. The full match model rates Mexico as the most likely winner at about 47.4%, with the draw around 29.1%. The key betting read is price discipline: the favourite is not clearly above model price at the best available book. This is a full match-result analysis using the current AU book prices, no-vig consensus model price, favourite strength, draw risk, and cross-book line shopping.",
    "markets": [
      {
        "market_matrix": "Full Match Model",
        "target_selection": "South Korea to Win",
        "true_price": 4.24,
        "current_odds": 4.2,
        "au_bookie": "Sportsbet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": null,
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Match to end in a Draw",
        "true_price": 3.44,
        "current_odds": 3.3,
        "au_bookie": "Sportsbet / PointsBet",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Sportsbet via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Sportsbet / PointsBet",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      },
      {
        "market_matrix": "Full Match Model",
        "target_selection": "Mexico to Win",
        "true_price": 2.11,
        "current_odds": 2,
        "au_bookie": "Neds / TAB",
        "odds_checked_at": "2026-06-13T20:56:07.950Z",
        "odds_updated_at": "2026-06-13T20:56:07.950Z",
        "odds_refresh_status": "checked_current",
        "odds_refresh_note": "Checked Neds via Odds API. Best available AU book price selected.",
        "best_price_tied_books": "Neds / TAB",
        "best_price_checked_books": "Sportsbet, Neds, TAB, PointsBet, BetRight"
      }
    ],
    "referee_last_checked": "2026-06-13T20:56:07.950Z",
    "referee_check_sources": "FIFA first when available; ESPN structured event feed fallback.",
    "referee_status": "not_verified",
    "referee_source": "No FIFA or ESPN referee assignment found during latest refresh.",
    "odds_last_checked": "2026-06-13T20:56:07.950Z",
    "odds_refresh_cadence": "four-to-one-hours-5-minute",
    "odds_refresh_note": "Matched Odds API event 0f2aeae6ac8e77223848d23a4ca86b0d."
  }
];
